name: onyx_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  device_preview: ^1.1.0
  dio: ^5.3.2
  skeletons: ^0.0.3
  shared_preferences: ^2.2.1
  get: 4.6.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

