Map<String, String> ar = {
  '': '',
  'password_not_matched': 'كلمتا المرور غير متطابقة',
  'enter_valid_pass': 'الرجاء إدخال كلمة مرور صالحة يجب أن تحتوي على 8 أحرف على الأقل',
  'enter_valid_email': 'يرجى إدخال عنوان بريد إلكتروني صالح',
  'enter_valid_name': 'يرجى إدخال اسم صالح',
  'enter_valid_phone': 'يرجى إدخال رقم هاتف صالح',
  'save': 'حفظ',
  'sign_out': 'تسجيل خروج',
  'we_work_with': 'نعمل مع',
  'who_are_we': 'من نحن',
  'contact_us': 'تواصل معنا',
  'soonInSaudi': 'قريباًفي السعودية',
  'launchDone': 'تم الاطلاق',
  'discoverSaudi': 'اكتشف السعودية',
  'next': 'التالي',
  'send_code': 'ارسال الرمز',
  'reset_password': 'إعادة تعيين كلمة المرور',
  'already_have_an_account': 'هل لديك حساب؟',
  'name': 'الاسم',
  'email': 'البريد الالكتروني',
  'new_registration': 'تسجيل جديد',
  'dont_have_acc': 'ليس لديك حساب؟ ',
  'did_you_forget_pass': 'هل نسيت كلمة المرور؟',
  'password': 'كلمة المرور',
  'confirm_password': 'تأكيد كلمة المرور',
  'mobile': 'رقم الجوال',
  'login': 'تسجيل الدخول',
  'soon_in_saudi': 'قريبا في السعودية',
};
