Map<String, String> en = {
  '': '',
  'password_not_matched': 'Confirm Password not matched',
  'enter_valid_pass': 'Please enter a valid password must contain 8 chars at least',
  'enter_valid_email': 'Please enter a valid email address',
  'enter_valid_name': 'Please enter a valid name',
  'enter_valid_phone': 'Please enter a valid phone',
  'save': 'Save',
  'sign_out': 'Sign Out',
  'we_work_with': 'We Work With',
  'who_are_we': 'Who Are We',
  'contact_us': 'Contact Us',
  'soonInSaudi': 'Soon in Saudi',
  'launchDone': 'Launch Done',
  'discoverSaudi': 'Discover Saudi',
  'next': 'Next',
  'send_code': 'Send Code',
  'reset_password': 'Reset password',
  'already_have_an_account': 'Already have an account?',
  'name': 'Name',
  'email': 'Email',
  'new_registration': 'New Registration',
  'dont_have_acc': 'Don\'t have an account? ',
  'did_you_forget_pass': 'Did you forget password?',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'mobile': 'Mobile',
  'login': 'Login',
  'soon_in_saudi': 'Soon in Saudi',
};
